### ISSUE TITLE
Include a kaccak implementation?

### ISSUE THREAD

**Issue by dcrewi** [DaGenix/rust-crypto#10]
[Someone ported][port] the kaccak reference implementation to rust. Since it is the winner for SHA-3, it might be within the scope of the project to include an implementation in rust-crypto (even if it's not that implementation)?

[port]: https://github.com/MarkJr94/rust-keccak

**Comment by calvinmetcalf** [comment]
sha3 and shake are subsets of keccak so a generic one could be written that is used to impliment the 6 versions from sha3 (4 drop in replacements for sha2 and then the 2 shake functions)

**Comment by sciyoshi** [comment]
I've taken a [Rust implementation of the SHA-3 (FIPS 202) by Sébastien Martini](https://github.com/seb-m/crypto.rs/blob/master/src/sha3.rs) and updated it to work with the latest versions of Rust. See #346 @DaGenix
