### ISSUE TITLE
Installation is broken due to obsolete syntax

### ISSUE THREAD

**Issue by ginsent** [DaGenix/rust-crypto#209]
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling rustc-serialize v0.2.4
   Compiling rust-crypto v0.2.10
src\rust-crypto\blockmodes.rs:1029:15: 1029:16 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\blockmodes.rs:1029             op: |&mut RefReadBuffer, &mut RefWriteBuffer, bool|
                                                 ^
note: use unboxed closures instead, no type annotation needed
src\rust-crypto\blockmodes.rs:1031:24: 1031:25 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\blockmodes.rs:1031             next_in_len: || -> uint,
                                                          ^
src\rust-crypto\blockmodes.rs:1032:25: 1032:26 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\blockmodes.rs:1032             next_out_len: || -> uint,
                                                           ^
src\rust-crypto\blockmodes.rs:1150:20: 1150:21 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\blockmodes.rs:1150             new_enc: || -> E,
                                                      ^
src\rust-crypto\blockmodes.rs:1151:20: 1151:21 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\blockmodes.rs:1151             new_dec: || -> D) {
                                                      ^
src\rust-crypto\blockmodes.rs:1200:20: 1200:21 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\blockmodes.rs:1200             new_enc: || -> E,
                                                      ^
src\rust-crypto\blockmodes.rs:1201:20: 1201:21 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\blockmodes.rs:1201             new_dec: || -> D) {
                                                      ^
src\rust-crypto\cryptoutil.rs:252:43: 252:44 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\cryptoutil.rs:252     fn input(&mut self, input: &[u8], func: |&[u8]|);
                                                                            ^
note: use unboxed closures instead, no type annotation needed
src\rust-crypto\cryptoutil.rs:406:51: 406:52 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\cryptoutil.rs:406     fn standard_padding(&mut self, rem: uint, func: |&[u8]|);
                                                                                    ^
src\rust-crypto\cryptoutil.rs:410:51: 410:52 error: obsolete syntax: `|uint| -> bool` closure type syntax
src\rust-crypto\cryptoutil.rs:410     fn standard_padding(&mut self, rem: uint, func: |&[u8]|) {
                                                                                    ^
error: aborting due to 10 previous errors
Could not compile `rust-crypto`.

To learn more, run the command again with --verbose.

**Comment by marcusklaas** [comment]
I'll try to open a pull request to fix this in the next hour.

**Comment by DaGenix** [comment]
I believe this is fixed with v0.2.11. Please re-open if its not. Thanks!

**Comment by DaGenix** [comment]
I'm not quite sure why #210 wouldn't work with `cargo test`. It looks like an issue with Rust and using `FnMut` trait objects. I think I've resolved it by using unboxed closures instead.
