### ISSUE TITLE
Can't compile on OSX 10.10

### ISSUE THREAD

**Issue by conradkleinespel** [DaGenix/rust-crypto#266]
Hello everyone,

I can't seem to compile the `master` branch of `rust-crypto` on OSX 10.10.2.

I get several compile errors about `rotate_left(s as usize)` expecting `u32` instead of `usize` in `src/md5.rs`:

![screenshot 2015-03-04 23 31 35](https://cloud.githubusercontent.com/assets/1234006/6495041/b572c750-c2c6-11e4-8100-936c3b9e8611.png)

So I tried removing ` as usize`. When I do that, I get a compiler error:

![screenshot 2015-03-04 23 32 00](https://cloud.githubusercontent.com/assets/1234006/6495042/b897eea6-c2c6-11e4-88b3-52ce897fb1e4.png)

These are the version of rustc/cargo I use:
```
rustc 1.0.0-nightly (fed12499e 2015-03-03) (built 2015-03-03)
cargo 0.0.1-pre-nightly (a58ffd7 2015-02-27) (built 2015-02-27)
```

Has anyone had similar issues ?

Thanks for your help.

**Comment by devigned** [comment]
Me too. I think this is related to: https://github.com/rust-lang/rust/issues/23037.

**Comment by DaGenix** [comment]
I'm seeing the same thing on my box - Kubuntu 15.04 beta-ish. I've pushed changes to fix the original problem - that rotate_left() now wants a u32 argument. I don't know how to work around rust-lang/rust#23037, however.

**Comment by devigned** [comment]
@DaGenix I was doing some digging, and found some code from sha2.rs that will reproduce the issue. It might be related to std::simd.

``` rust
#[inline]
fn sha256load(v2: u32x4, v3: u32x4) -> u32x4 {
    u32x4(v3.3, v2.0, v2.1, v2.2)
}

/// Emulates `llvm.x86.sha256msg1` intrinsic.
#[inline]
fn sha256msg1(v0: u32x4, v1: u32x4) -> u32x4 {

    // sigma 0 on vectors
    //#[inline]
    fn sigma0x4(x: u32x4) -> u32x4 {
        ((x >> u32x4( 7,  7,  7,  7)) | (x << u32x4(25, 25, 25, 25))) ^
        ((x >> u32x4(18, 18, 18, 18)) | (x << u32x4(14, 14, 14, 14))) ^
         (x >> u32x4( 3,  3,  3,  3))
    }

    v0 + sigma0x4(sha256load(v0, v1))
}
```

**Comment by devigned** [comment]
In fact, I think it can be narrowed down to the addition of v0 and sigma0x4(sha256load(v0, v1)):

``` rust
v0 + sigma0x4(sha256load(v0, v1))
```

**Comment by DaGenix** [comment]
I tried commenting out the sha2 module and everything that depends on it and I still hit the ICE. Based on the comments from rust-lang/rust#23037, it looks like this is related using SIMD types with overflow checking on. Unfortunately, a bunch of modules use SIMD types, including Sha2. Anyway, I have a workaround for that mostly ready, I think: If ndebug is defined, use the normal SIMD types. However, if its not defined, then fall back to manually implemented SIMD-like types. These will be super slow, but, they compile fine. However, then we hit the next problem:  Rust-Crypto is filled to the brim with integer operations that expect to be able to wrap. So, even with the SIMD workaround for the ICE, basically nothing works anyway due to all the use of wrapping arithmetic. I'll work on this over the weekend, but, it looks like lots of stuff needs to change. Maybe I'm missing an easier solution?

Right now, the best workaround seems to be to compile with "--release". That avoids the ICE and all the tests work fine that way.

**Comment by devigned** [comment]
@DaGenix I suppose I wasn't totally clear. It's definitely SIMD based and not really related to sha2.rs.

I was just posting that code to give an example that causes the ICE. I had commented out everything but this code.

Thanks for finding the "--release" work around.

**Comment by DaGenix** [comment]
@devigned Sorry - it was late when I responded and I misread your comment. I think we're in agreement as to the problem, unfortunately the solution looks to be a bit of a pain. I'll poke at it and hopefully its easier to resolve than I'm guessing.

**Comment by devigned** [comment]
No worries. You're doing awesome work. Thank you.

It would be a bummer to have to move away from SIMD types to SIMD like types.

**Comment by superalsrk** [comment]
Hi, when i use rust-crytpo 0.2.22  in my project, something compiles wrong

```
▶ cargo build --verbose
       Fresh gcc v0.3.1
       Fresh libc v0.1.2
       Fresh log v0.2.5
       Fresh rustc-serialize v0.3.1
       Fresh rand v0.2.0
       Fresh time v0.1.19
   Compiling rust-crypto v0.2.22
     Running `rustc /Users/stackbox/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-crypto-0.2.22/src/lib.rs --crate-name crypto --crate-type lib -g -C metadata=610ca9f9a5ece906 -C extra-filename=-610ca9f9a5ece906 --out-dir /Users/stackbox/Project/Private/rust-qiniu/target/deps --emit=dep-info,link -L dependency=/Users/stackbox/Project/Private/rust-qiniu/target/deps -L dependency=/Users/stackbox/Project/Private/rust-qiniu/target/deps --extern rustc-serialize=/Users/stackbox/Project/Private/rust-qiniu/target/deps/librustc-serialize-2aa16a9a901fcba8.rlib --extern rand=/Users/stackbox/Project/Private/rust-qiniu/target/deps/librand-ca65baa6486b24a1.rlib --extern time=/Users/stackbox/Project/Private/rust-qiniu/target/deps/libtime-f5c2f62bb1bdf976.rlib -Awarnings -L native=/Users/stackbox/Project/Private/rust-qiniu/target/build/time-f5c2f62bb1bdf976/out`
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'tried to get overflow intrinsic for non-int type', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustc_trans/trans/expr.rs:2358

stack backtrace:
   1:        0x10bb8626d - sys::backtrace::write::h4102628905e599dfKDA
   2:        0x10bbafc34 - panicking::on_panic::hc3e357b7ac1634e3MsJ
   3:        0x10bae1279 - rt::unwind::begin_unwind_inner::h53ac351c4bf63bfaibJ
   4:        0x10879b6ff - rt::unwind::begin_unwind::h18004612905053568604
   5:        0x1088599b8 - trans::expr::with_overflow_check::hf66ced1897de0d922nk
   6:        0x108857f75 - trans::expr::trans_eager_binop::h40269c025c3b5908Yrj
   7:        0x10883ae11 - trans::expr::trans_assign_op::hff0530381bf506fa70j
   8:        0x10882676d - trans::expr::trans_rvalue_stmt_unadjusted::h157538367858c8f7Nwi
   9:        0x1087df1fa - trans::expr::trans_into::hdc71121cfd90aad8Tph
  10:        0x1087de330 - trans::controlflow::trans_stmt_semi::ha7b7a5b089d60327I6d
  11:        0x1087dfc23 - trans::controlflow::trans_block::h8b9a575f721ab2afv7d
  12:        0x1088226a0 - trans::expr::trans_rvalue_dps_unadjusted::h8dd9ce1cfde4b166yCi
  13:        0x1087df0bb - trans::expr::trans_into::hdc71121cfd90aad8Tph
  14:        0x1087de330 - trans::controlflow::trans_stmt_semi::ha7b7a5b089d60327I6d
  15:        0x1087dfc23 - trans::controlflow::trans_block::h8b9a575f721ab2afv7d
  16:        0x1088226a0 - trans::expr::trans_rvalue_dps_unadjusted::h8dd9ce1cfde4b166yCi
  17:        0x1087df0bb - trans::expr::trans_into::hdc71121cfd90aad8Tph
  18:        0x1088bd3b9 - trans::_match::trans_match_inner::hbaadee047d22523d3Kw
  19:        0x108822660 - trans::expr::trans_rvalue_dps_unadjusted::h8dd9ce1cfde4b166yCi
  20:        0x1087df0bb - trans::expr::trans_into::hdc71121cfd90aad8Tph
  21:        0x1087dff8a - trans::controlflow::trans_block::h8b9a575f721ab2afv7d
  22:        0x108826434 - trans::expr::trans_rvalue_stmt_unadjusted::h157538367858c8f7Nwi
  23:        0x1087df1fa - trans::expr::trans_into::hdc71121cfd90aad8Tph
  24:        0x1088bd3b9 - trans::_match::trans_match_inner::hbaadee047d22523d3Kw
  25:        0x108822660 - trans::expr::trans_rvalue_dps_unadjusted::h8dd9ce1cfde4b166yCi
  26:        0x1087df0bb - trans::expr::trans_into::hdc71121cfd90aad8Tph
  27:        0x1088d309e - trans::_match::mk_binding_alloca::h10088925327053054383
  28:        0x1087de4a8 - trans::base::init_local::h28a4183a765998a3GBs
  29:        0x1087dfc52 - trans::controlflow::trans_block::h8b9a575f721ab2afv7d
  30:        0x1088226a0 - trans::expr::trans_rvalue_dps_unadjusted::h8dd9ce1cfde4b166yCi
  31:        0x1087df0bb - trans::expr::trans_into::hdc71121cfd90aad8Tph
  32:        0x1087de330 - trans::controlflow::trans_stmt_semi::ha7b7a5b089d60327I6d
  33:        0x1087dfc23 - trans::controlflow::trans_block::h8b9a575f721ab2afv7d
  34:        0x1088a177a - trans::base::trans_closure::h04217c26eb7081b3ent
  35:        0x1087ce4af - trans::base::trans_fn::hf9446782d179d8da7xt
  36:        0x1087caaac - trans::base::trans_item::h865f8f17c1fe69f2ZVt
  37:        0x1087ca2ab - trans::base::trans_item::h865f8f17c1fe69f2ZVt
  38:        0x1088a85cb - trans::base::trans_crate::h6a5b18ffa3c8b086aSu
  39:        0x1082a0837 - driver::phase_4_translate_to_llvm::h403abcd26e929613gOa
  40:        0x10827c1b6 - driver::compile_input::hb5f376d824cdbd3fNba
  41:        0x108349be6 - run_compiler::h771e8a13e5d39fa8G6b
  42:        0x1083472d0 - thunk::F.Invoke<A, R>::invoke::h7762305853454838659
  43:        0x108345e0f - rt::unwind::try::try_fn::h12334561919016735610
  44:        0x10bc29ca8 - rust_try_inner
  45:        0x10bc29c95 - rust_try
  46:        0x10834662f - thunk::F.Invoke<A, R>::invoke::h11009727036119889909
  47:        0x10bb9b3e2 - sys::thread::thread_start::h45ac84d363b9c45b32E
  48:     0x7fff8976b267 - _pthread_body
  49:     0x7fff8976b1e4 - _pthread_start

Could not compile `rust-crypto`.

Caused by:
  Process didn't exit successfully: `rustc /Users/stackbox/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-crypto-0.2.22/src/lib.rs --crate-name crypto --crate-type lib -g -C metadata=610ca9f9a5ece906 -C extra-filename=-610ca9f9a5ece906 --out-dir /Users/stackbox/Project/Private/rust-qiniu/target/deps --emit=dep-info,link -L dependency=/Users/stackbox/Project/Private/rust-qiniu/target/deps -L dependency=/Users/stackbox/Project/Private/rust-qiniu/target/deps --extern rustc-serialize=/Users/stackbox/Project/Private/rust-qiniu/target/deps/librustc-serialize-2aa16a9a901fcba8.rlib --extern rand=/Users/stackbox/Project/Private/rust-qiniu/target/deps/librand-ca65baa6486b24a1.rlib --extern time=/Users/stackbox/Project/Private/rust-qiniu/target/deps/libtime-f5c2f62bb1bdf976.rlib -Awarnings -L native=/Users/stackbox/Project/Private/rust-qiniu/target/build/time-f5c2f62bb1bdf976/out` (exit code: 101)
```

**Comment by DaGenix** [comment]
Right now, rust-crypto won't work unless its compiled with "--release". So, I believe that "cargo build --release" should work for you. The issue is that without "--release", arithmetic overflow checking is on, which breaks usage of SIMD types and also causes all sorts of failures all over the place. I'm working on a fix.

**Comment by DaGenix** [comment]
Er, please ignore most of that last comment. My fingers typed faster than my brain. I see you are using 0.2.22, which, I hoped would work by virtue of forcing optimizations and disabling debug. Apparently I was wrong about that - sorry. What version of Rust are you using? I assume that you are seeing the build error while compiling your code, which depends on rust-crypto as opposed to compiling rust-crypto directly, is that correct?

**Comment by superalsrk** [comment]
@DaGenix   Yeah you supposition is  right,  My rust version is  **rustc 1.0.0-nightly (built 2015-03-07)**  , 

here is my [lib.rs](https://github.com/superalsrk/rust-qiniu/blob/develop/src/lib.rs) , Thx for your reply!

**Comment by DaGenix** [comment]
Hrm, well, it appears that the quick hack I included in 0.2.22 to try to get everything working again doesn't work. I'm (hopefully) finishing up the real fix now. With a little luck, I'll publish 0.2.23 soon with all the wrapping arithmetic using the wrapping arithmetic operators along with a workaround for the SIMD bug.

**Comment by rolandshoemaker** [comment]
Works on Ubuntu x86_64 14.04 here when compiling as a dep! (with `--release` anyway)

**Comment by DaGenix** [comment]
I just pushed v0.2.23 which should fix all of these issues. I found all the places that operations were underflowing or overflowing and used the wrapping versions of add, sub, or mul. Please let me know if anyone is still having issues.

@devigned With Rust 1.0, I believe that the SIMD types will not be stabilized. I'd really like Rust-Crypto to work with Rust 1.0, so, I think we'll need a mechanism to make the library work without SIMD types. What I'm hoping is that we can support Rust 1.0 using some sort of hack to avoid using built in SIMD types (possibly something like this "fake-SIMD" module that I build to workaround rust-lang/rust#23037) while still using real SIMD types when compiling with a Rust nightly. I don't see any reason we'd have to move away from SIMD types altogether, but, some configurations may not be able to use them. With v0.2.23, test configurations now use the fake-SIMD types. However, release configurations continue to use the real SIMD types.
