### ISSUE TITLE
Building fails on Windows during build scripts

### ISSUE THREAD

**Issue by debuuu** [DaGenix/rust-crypto#299]
I've been using rust-crypto for a good while now in a small Rust project, and after a month where I wasn't able to touch it, I came back and updated the Rust compiler and tried to build. Rust-crypto won't build though, the build script fails seeming, ending in this:

thread '<main>' panicked at 'explicit panic', C:\msys32\home\Machine\\.cargo\registry\src\github.com-1285ae84e5963aae\gcc-0.3.4\src\lib.rs:380

I'm on Windows 8, using the 32bit Rust compiler, installed fresh today (tried both the beta version and the nightly, currently on today's build of the nightly).

As the build seems to be running through on Travis I assume something's wrong with my setup, but I have no idea what I might need to change; apologies if this is a simple fix and I'm wasting your time!

**Comment by zcdziura** [comment]
Do you have GCC installed on your computer? The `gcc` crate invokes the gcc compiler found on most Linux/Unix systems.

**Comment by jmquigs** [comment]
It builds for me on windows 7, but I did have to install MinGW and make sure its "gcc" was in my path.  The bundled gcc that ships with rust is not sufficient because it doesn't actually have any c header files, so it can't build the helpers this project requires.  See https://github.com/alexcrichton/gcc-rs/issues/7

**Comment by debuuu** [comment]
I do have GCC installed yeah, I installed some MinGW variation in order to be able to compile the ```hyper``` crate. @jmquigs, which installation did you use? 

Anyway, I tried to compile this crate again, and now have a bunch of different errors, though still coming from the build script. Here's a snippet, they're all similar:

```
running: "gcc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-mwin32" "-m3
2" "c:/Users/blah\.cargo\registry\src\github.com-121aea75f9ef2ce2\rust-cry
pto-0.2.31\src/aesni_helpers.c" "-o" "d:\Rust\mcm_playground\target\debug\build\
rust-crypto-017070612ce33417\out\src\aesni_helpers.o"

command did not execute successfully, got: exit code: 1

--- stderr
c:/Users/blah\.cargo\registry\src\github.com-121aea75f9ef2ce2\rust-crypto-
0.2.31\src/aesni_helpers.c: In function 'rust_crypto_aesni_aesimc':
c:/Users/blah\.cargo\registry\src\github.com-121aea75f9ef2ce2\rust-crypto-
0.2.31\src/aesni_helpers.c:12:5: error: unknown register name 'xmm1' in 'asm'
     asm(
     ^
```

There are quite a few more, referencing different unknown registers. Any ideas..?

**Comment by jmquigs** [comment]
@debuuu, It seems easy to get the wrong mingw version.  I installed on another machine and used the mingw installer, and it did not work, though I did not have the same errors as you.

What did work was to install MSYS2, then install mingw from there as described in the rust guide: https://github.com/rust-lang/rust#building-on-windows (steps 1 & 2).  I used the 64 bit toolchain: 
```sh
$ pacman -S mingw-w64-x86_64-toolchain
$ pacman -S base-devel
```

When you install the toolchain, it gives you a submenu of options.  I think I just installed "mingw-w64-x86_64-gcc", and it picked up the dependencies, but there is an "all" option as well.

I also had to make sure that gcc was in my path (I used a user environment variable).  After restarting my shell, I could build with cargo both from the msys shell and regular windows command prompt.  Below is the output from my gcc installation
```code
$ gcc --version
gcc.exe (Rev5, Built by MSYS2 project) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ which gcc
/mingw64/bin/gcc
$ which as
/mingw64/bin/as
$ which ar
/mingw64/bin/ar
$ which ld
/mingw64/bin/ld
```

**Comment by debuuu** [comment]
@jmquigs, So, I followed your instructions, and firstly tried the 32bit version, from which I got the same errors. So then I tried the 64bit version and now it appears to compile! Thanks a lot!

I don't know if this is a known issue relating to this package, but if it is it might be useful to have it in the readme?
