### ISSUE TITLE
AEAD nonce reuse question

### ISSUE THREAD

**Issue by hroi** [DaGenix/rust-crypto#306]
You are taking nonce as a parameter in the contructor:
 pub fn new (key_size: KeySize, key: &[u8], nonce: &[u8], aad: &[u8]) -> AesGcm<'a>

Intuitively this would mean that the instance can only be used for encrypting a single message before it must be destroyed as otherwise the nonce would be reused.

Is this correct?

**Comment by tcosprojects** [comment]
Yes. There is a flag self.finished that gets set in the encrypt() method which allows it to only be called once to prevent accidental nonce re-use.
