### ISSUE TITLE
rust-crypto-0.2.31 does not build on 32-bit Xubuntu 14.04, TARGET = Some("i686-unknown-linux-gnu")

### ISSUE THREAD

**Issue by mabeebam** [DaGenix/rust-crypto#307]
When I try to compile rust-crypto-0.2.31 on a target = Some("i686-unknown-linux-gnu") within a cargo build of some project (cargo-version: cargo 0.3.0-nightly (c8c1624 2015-06-26) (built 2015-06-26), rustc-version: rustc 1.3.0-dev (773052a60 2015-06-27)), I get the following errors:

Process didn't exit successfully: `<my_project_home_path>/target/debug/build/rust-crypto-017070612ce33417/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("i686-unknown-linux-gnu")
TARGET = Some("i686-unknown-linux-gnu")
CARGO_MANIFEST_DIR = Some("<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31")
OUT_DIR = Some("<my_project_home_path>/target/debug/build/rust-crypto-017070612ce33417/out")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
debug 0
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CFLAGS_i686-unknown-linux-gnu = None
CFLAGS_i686_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-m32" "<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/util_helpers.c" "-o" "<my_project_home_path>/target/debug/build/rust-crypto-017070612ce33417/out/src/util_helpers.o"
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
debug 0
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CFLAGS_i686-unknown-linux-gnu = None
CFLAGS_i686_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-m32" "<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c" "-o" "<my_project_home_path>/target/debug/build/rust-crypto-017070612ce33417/out/src/aesni_helpers.o"

command did not execute successfully, got: exit code: 1

--- stderr
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c: In function ‘rust_crypto_aesni_aesimc’:
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:12:5: error: unknown register name ‘xmm1’ in ‘asm’
     asm(
     ^
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c: In function ‘rust_crypto_aesni_setup_working_key_128’:
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:27:5: error: unknown register name ‘xmm3’ in ‘asm’
     asm(
     ^
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:27:5: error: unknown register name ‘xmm2’ in ‘asm’
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:27:5: error: unknown register name ‘xmm1’ in ‘asm’
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c: In function ‘rust_crypto_aesni_setup_working_key_192’:
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:80:5: error: unknown register name ‘xmm3’ in ‘asm’
     asm(
     ^
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:80:5: error: unknown register name ‘xmm2’ in ‘asm’
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:80:5: error: unknown register name ‘xmm1’ in ‘asm’
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c: In function ‘rust_crypto_aesni_setup_working_key_256’:
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:168:5: error: unknown register name ‘xmm3’ in ‘asm’
     asm(
     ^
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:168:5: error: unknown register name ‘xmm2’ in ‘asm’
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:168:5: error: unknown register name ‘xmm1’ in ‘asm’
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c: In function ‘rust_crypto_aesni_encrypt_block’:
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:266:5: error: unknown register name ‘xmm1’ in ‘asm’
     asm(
     ^
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:266:5: error: unknown register name ‘xmm0’ in ‘asm’
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c: In function ‘rust_crypto_aesni_decrypt_block’:
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:303:5: error: unknown register name ‘xmm1’ in ‘asm’
     asm(
     ^
<my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/rust-crypto-0.2.31/src/aesni_helpers.c:303:5: error: unknown register name ‘xmm0’ in ‘asm’
thread '<main>' panicked at 'explicit panic', <my_home_path>/.cargo/registry/src/github.com-121aea75f9ef2ce2/gcc-0.3.8/src/lib.rs:497

**Comment by vi** [comment]
Me too. Can't build rust-coreutils because of that.

**Comment by Zebedee68** [comment]
error: unknown register name 'xmm1' in 'asm' requires 
     export CFLAGS="-mmmx -msse"
to remove 64bit operands,
the CFLAGS should be set in the appropriate build script - I have no idea where this is, anyone?

**Comment by mcarpenter** [comment]
Same problem on Ubuntu 14.04 64 bit. @Zebedee68's workaround above is good though.

**Comment by DaGenix** [comment]
Thanks for the report and sorry for taking so long to get to this. It looks like GCC is refusing to compile assembly code that uses the SSE registers for targets that don't support SSE. Kinda annoying - the code would only actually be called if the `CPUID` instruction reports that the AES-NI instructions are supported which will only occur on processors that also support SSE. I think #320 fixes this problem by skipping the assembly blocks when SSE is not supported by the target. Please let me know if you still see any issues.
