### ISSUE TITLE
RS(256, 384, 512) - no supports for these?

### ISSUE THREAD

**Issue by GildedHonour** [DaGenix/rust-crypto#309]
Does it support RS(256, 384, 512)? It seems it doesn't. Are you going to add this capacity soon?

**Comment by passcod** [comment]
These identifiers are RFC7518 identifiers for RSASSA-PKCS1-v1_5 using SHA-(256, 384, 512). The SHA2 hashes are implemented, and the DH/RSA implementation progress is tracked in #106.

**Comment by GildedHonour** [comment]
Maybe you know what can I use instead of this library for RSA for now?

**Comment by passcod** [comment]
[OpenSSL](https://github.com/sfackler/rust-openssl), probably.
