### ISSUE TITLE
Processing input by parts

### ISSUE THREAD

**Issue by DoumanAsh** [DaGenix/rust-crypto#310]
Is it possible to to proceed content by parts?
For example if file is too big to load it into memory, it would be more preferably to proceed it by chunks.
But it seems as of current it is not possible. At least in my experiment generated hash is not correct(and not the same) comparing to the one generated by inputting the whole file.
It is also strange because, as i see in Md5 struct, flag ```finished``` should be set only when i call result_str()
And i think a similar logic should be applied to all other hash algorithms

Just example of what i'm trying
```
fn calc_checksum(path: &str) {
    if let Ok(file) = std::fs::File::open(&path) {
        let mut file = BufReader::new(file);
        let mut file_content: [u8; 10000] = [0; 10000];
        let mut md5_sum = Md5::new();
        let mut sha1_sum = Sha1::new();
        let mut sha256_sum = Sha256::new();
        let mut sha512_sum = Sha512::new();

        println!(">>>{}:", &path);
        loop {
            let read_bytes = file.read(&mut file_content).unwrap();
            println!("read {} bytes", read_bytes);
            if read_bytes == 0 { break; }

            md5_sum.input(&file_content);
            sha1_sum.input(&file_content);
            sha256_sum.input(&file_content);
            sha512_sum.input(&file_content);
        }
        println!("MD5:   {}", md5_sum.result_str());
        println!("SHA1:  {}", sha1_sum.result_str());
        println!("SHA256:{}", sha256_sum.result_str());
        println!("SHA512:{}", sha512_sum.result_str());
        println!("=======================================================\n");
    }
    else {
        println!(">>>{}: failed to open", &path);
    }
}
```

**Comment by marcusklaas** [comment]
Your approach is mostly correct, but I believe you shouldn't pass the entire buffer to the hashing struct. This produces incorrect results when the buffer is only partially filled with 'fresh' data.

Instead, try
```rust
md5_sum.input(&file_content[..read_bytes]);
```

**Comment by DoumanAsh** [comment]
Aw... that was very stupid of me... Totally forgot that read is not necessary fills buffer completely.
Thank you for correction.
Sorry for bother
