### ISSUE TITLE
Usage for passwords hashing

### ISSUE THREAD

**Issue by e-oz** [DaGenix/rust-crypto#331]
Hello.
Please provide an example how to use this library to get string(!) representation of password hash, using bcrypt or bcrypt_pbkdf (to store it in DB) and how to check later password matching stored hash (what is even more interesting, since I can't find any functions in source code to do this).

**Comment by dariusc93** [comment]
@e-oz it is pretty easy. The way I do it is use `String::from_utf8_lossy` for the hash and also put it into hex.

**Comment by beznez** [comment]
Hi, I'm relatively new to Rust and I'm looking to do the same thing. I looked at `String::from_utf8_lossy` but I'm not sure what the `input` should be. This is what I have so far:

```
extern crate crypto;

use crypto::bcrypt_pbkdf::bcrypt_pbkdf;

fn main() {
    let mut out = [0u8; 32];
    bcrypt_pbkdf(b"password", b"salt", 10, &mut out);
    let mut password_hash = String::with_capacity(out.len() * 2);
    for c in out.iter() {
        password_hash.push_str(&format!("{}", c));
    }
    println!("Hash: {}", password_hash);
}
```

Could you provide a code example to get a string using `bcrypt_pbkdf`? I want to get a hash that looks like `$2y$10$QPLlURPYklGo.KZfZLDUne/zro3Am7KGKKoRprBCd4FmYZLzaZwsy` as a string so that I can insert that into a database.

**Comment by e-oz** [comment]
@beznez I didn't find way to check password against hash with bcrypt, so I use scrypt:

```rust
extern crate crypto;
use self::crypto::scrypt;

pub fn get_password_hash(password: &str) -> String {
	let params = scrypt::ScryptParams::new(16, 4, 1);
	scrypt::scrypt_simple(password,  &params).unwrap_or("".to_string())
}

pub fn check_password_hash(password: &str, hash: &str) -> bool {
	match scrypt::scrypt_check(password, hash){
		Ok(pwd) => {
			pwd
		},
		Err(_) => {
			false
		}
	}
}
```

**Comment by Racum** [comment]
@beznez, did you find a way to generate the hash in the format you described? I'm having the same problem here.

**Comment by beznez** [comment]
No, I wasn't able to get it working. At work we decided to go with another solution so I never completed it. Good luck.
