### ISSUE TITLE
Possible bug with bcrypt implementation

### ISSUE THREAD

**Issue by dariusc93** [DaGenix/rust-crypto#332]
This morning ive tested bcrypt and noticed that if the cost is at 31 (max cost apparently) that computing the hash is under a second while using the cost of 10 or 12 would be between 2 to 9 seconds. On Go or any language with bcrypt implementation, I've noticed that it would take a long time to compute the hash with the cost of 31. Is the implementation suppose to be as like this or could this be a bug in the implementation that should be addressed?

**Comment by mbrubeck** [comment]
Good catch.  PR #349 has a fix.  **Warning:** Until a fix is merged, trying to use bcrypt with cost=31 will actually use cost=0.
