### ISSUE TITLE
Compilation error on nightly due to Clone derive pragma on Blowfish

### ISSUE THREAD

**Issue by netvl** [DaGenix/rust-crypto#335]
When using the latest Rust nightly (currently `rustc 1.6.0-nightly (aad4e5665 2015-12-05)`) rust-crypto fails to compile with the following error:

```
src/blowfish.rs:13:5: 13:23 error: the trait `core::clone::Clone` is not implemented for the type `[u32; 256]` [E0277]
src/blowfish.rs:13     s: [[u32; 256]; 4],
                       ^~~~~~~~~~~~~~~~~~
src/blowfish.rs:11:10: 11:15 note: in this expansion of #[derive_Clone] (defined in src/blowfish.rs)
src/blowfish.rs:13:5: 13:23 help: run `rustc --explain E0277` to see a detailed explanation
src/blowfish.rs:13:5: 13:23 note: required by `core::clone::Clone::clone`
error: aborting due to previous error
Could not compile `rust-crypto`.
```

I think this may be caused by rust-lang/rust#30130 but I'm not sure.

**Comment by netvl** [comment]
The relevant PR [was reverted](https://github.com/rust-lang/rust/pull/30247) in Rust repo, so I guess this can be closed because the next nightly should work correctly again.

**Comment by bluss** [comment]
@netvl Thanks for reporting the regression!
