### ISSUE TITLE
Panics at 102 of blockmodes.rs

### ISSUE THREAD

**Issue by Spencer-H** [DaGenix/rust-crypto#381]
Running in debug mode, line 102 of blockmodes.rs will cause an overflowing subtract.

This is reproducible by passing an iv of larger than 16 to the AES example that is given. 

If iv's are not supposed to be larger than this, it should be explicitly stated with a custom panic message.

**Comment by niluxv** [comment]
Added assert iv length to [Rust-crypto-maintained](https://github.com/niluxv/rust-crypto).
Thank you.
