### ISSUE TITLE
Sha3 512-bit does not provide result bytes

### ISSUE THREAD

**Issue by kellenfujimoto** [DaGenix/rust-crypto#408]
A given `Sha3::sha3_512` instance will not write result bytes, but will return the correct result_str.

`result_str()` shows expected behavior:
``` rust
let mut hasher = Sha3::sha3_512();
hasher.input_str("test");
println!("{}", hasher.result_str());
```
Prints `9ece086...` etc.

`result()` does not show expected behavior:
``` rust
let mut hasher = Sha3::sha3_512();
hasher.input_str("test");
let mut result: Vec<u8> = Vec::with_capacity(64);
hasher.result(&mut result);
println!("{:?}", result);
```
Prints `[]`. I expect `[57, 101, 99, 101, 48...` etc.

**Comment by burdges** [comment]
`Vec::with_capacity` only allocates space, without placing any data into the `Vec`, so you're passing result an empty slice.  Try `vec![0u8; 64]` instead.  Or just `let mut result = [0u8; 64];` if you want your buffer on the stack.

**Comment by burdges** [comment]
Anyways this issue can be closed.
