### ISSUE TITLE
Does rust crypto support certificate validation?

### ISSUE THREAD

**Issue by iddm** [DaGenix/rust-crypto#416]
Will this project ever have such a feature? I would get rid of OpenSSL crate and library at all if such a feature were implemented.

**Comment by briansmith** [comment]
@vityafx This crate operates at a lower layer than certificates. The [webpki](https://github.com/briansmith/webpki) crate does certificate validation.

**Comment by iddm** [comment]
Thanks. I have just thought this crate is something like OpenSSL in pure rust. It seems it is not. Thank you for your fast response.
