### ISSUE TITLE
AES-CBC padding buffer length passed to PaddingProcessor is too short

### ISSUE THREAD

**Issue by drahnr** [DaGenix/rust-crypto#426]
Decrypting a a 32byte payload with AES-CBC with a key of 256bit and iv of 128bit and a custom padding scheme (\n followed by \0, legacy code compat) the stream buffer available to 
```
fn strip_output<R: ReadBuffer>(&mut self, output_buffer: &mut R) -> bool {
```
`output_buffer` has only a length of 16 bytes and not 32 as I would have expected.

This was determined by `output_buffer.peek_remaining().len()`

**Comment by musoke** [comment]
Doesn't AES always have 128 bits for the block size? 256 refers to the key size.

**Comment by drahnr** [comment]
Yes you are right, block size is 128bits - always - independent of the key length. My issues were elsewhere. Sorry for the noise.
