### ISSUE TITLE
Incorrect HMAC sha256 value returned

### ISSUE THREAD

**Issue by KallDrexx** [DaGenix/rust-crypto#431]
Based on the HMAC specification (https://tools.ietf.org/html/rfc4868#section-2.7) it seems like rust-crypto is returning incorrect values based on the following test:

```
    #[test]
    fn hmac_test2() {
        let data = "Hi There".as_bytes();
        let key = [0x0b; 20];
        let mut digest = Sha256::new();
        digest.input(&data);

        let mut hmac = Hmac::<Sha256>::new(digest, &key);
        let result = hmac.result();
        let code = result.code();

        let expected = [176_u8, 52_u8, 76_u8, 97_u8, 216_u8, 219_u8, 56_u8, 83_u8, 92_u8, 168_u8, 175_u8, 206_u8, 175_u8, 11_u8, 241_u8, 43_u8, 136_u8, 29_u8, 194_u8, 0_u8, 201_u8, 131_u8, 61_u8, 167_u8, 38_u8, 233_u8, 55_u8, 108_u8, 46_u8, 50_u8, 207_u8, 247_u8];

        assert_eq!(&expected[..], &code[..]);
    }
```

> ---- handshake::tests::hmac_test2 stdout ----
>        thread 'handshake::tests::hmac_test2' panicked at 'assertion failed: `(left == right)`
>  left: `[176, 52, 76, 97, 216, 219, 56, 83, 92, 168, 175, 206, 175, 11, 241, 43, 136, 29, 194, 0, 201, 131, 61, 167, 38, 233, 55, 108, 46, 50, 207, 247]`,
> right: `[202, 153, 85, 27, 117, 53, 17, 105, 88, 244, 48, 64, 123, 53, 206, 131, 198, 97, 109, 115, 144, 126, 12, 158, 115, 140, 252, 124, 229, 138, 21, 82]`', src\handshake\mod.rs:367:8

**Comment by niluxv** [comment]
Strange that there are no hmac + sha tests in the project.

Your test fails because you pass the data to sha256 (the collision resistant hashfunction) and not to hmac. You should change your test to:

```
    #[test]
    fn hmac_test2() {
        let data = "Hi There".as_bytes();
        let key = [0x0b; 20];
        let mut digest = Sha256::new();
        //digest.input(&data); // <-- remove this line

        let mut hmac = Hmac::<Sha256>::new(digest, &key);
        hmac.input(&data); // <-- add this line
        let result = hmac.result();
        let code = result.code();

        let expected = [176_u8, 52_u8, 76_u8, 97_u8, 216_u8, 219_u8, 56_u8, 83_u8, 92_u8, 168_u8, 175_u8, 206_u8, 175_u8, 11_u8, 241_u8, 43_u8, 136_u8, 29_u8, 194_u8, 0_u8, 201_u8, 131_u8, 61_u8, 167_u8, 38_u8, 233_u8, 55_u8, 108_u8, 46_u8, 50_u8, 207_u8, 247_u8];

        assert_eq!(&expected[..], &code[..]);
    }
```

PS: You called the test function hmac_test**2**. Does this mean you have written more tests? If so, could you commit or PR them to [https://github.com/niluxv/rust-crypto](https://github.com/niluxv/rust-crypto) (if you agree to publish them under the MIT and APACHE2.0 licences)? Every new test is helpful.

**Comment by KallDrexx** [comment]
Hi, thanks for the response!

That makes sense, I wonder if I just didn't notice there was an input function on hmac.  The documentation didn't really have examples so I was kind of flailing about trying to get an hmac to calculate.

While the code this was written in was MIT, the reason that's `hmac_test2()` was because my `hmac_test()` function was testing a custom `calc_hmac()` function I had written that takes two strings, concatenates them, then calculates the hmac for them (required for the RTMP protocol handshake, which is what I was implementing).    The `hmac_test2()` test was just an attempt to rule out my custom code and figure out what I was doing wrong in trying to get any hmac to calculate correctly.

Feel free to copy this test over though and use it.

**Comment by newpavlov** [comment]
@KallDrexx 
If you need just HMAC-SHA256 take a look at [RustCrypto](https://github.com/RustCrypto)'s [`hmac`](https://docs.rs/hmac/) and [`sha2`](https://docs.rs/sha2/) crates. They are significantly smaller than (currently unmaintained) `rust-crypto` and written in pure Rust.
