### ISSUE TITLE
util_helper.c failed to compile with target x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by gaamdalurt** [DaGenix/rust-crypto#436]
Compilation output:
   Compiling rust-crypto v0.2.36
error: failed to run custom build command for `rust-crypto v0.2.36`
process didn't exit successfully: `/home/gaamda/Projects/gcrypto/target/release/build/rust-crypto-f7c4f8a36d695705/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
TARGET_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
CROSS_COMPILE = None
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "/Fo/home/gaamda/Projects/gcrypto/target/x86_64-pc-windows-msvc/release/build/rust-crypto-92e07b808030a8f7/out/src/util_helpers.o" "/c" "src/util_helpers.c"
cargo:warning=cc: error: /Fo/home/gaamda/Projects/gcrypto/target/x86_64-pc-windows-msvc/release/build/rust-crypto-92e07b808030a8f7/out/src/util_helpers.o: No such file or directory
cargo:warning=cc: error: /c: No such file or directory
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "/Fo/home/gaamda/Projects/gcrypto/target/x86_64-pc-windows-msvc/release/build/rust-crypto-92e07b808030a8f7/out/src/util_helpers.o" "/c" "src/util_helpers.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/gaamda/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: gcc::fail
   8: gcc::Build::compile
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start

Wanted to cross-compile. Tell me if I can do any test or so, I will. 
Thanks for all the work :)

**Comment by dariusc93** [comment]
I do not believe this project is active anymore. It havent been updated in a couple of years afterall.

**Comment by gaamdalurt** [comment]
Sure, haven't noticed it. The code compile in regular windows toolchain, the problem is in my configuration. :(

So, it is not anymore a bug, afterall. :)
(thanks anyway for the reply)

**Comment by zydxhs** [comment]
How did you solve it?
I have the same problem.
