### ISSUE TITLE
gcc is deprecated

### ISSUE THREAD

**Issue by HTGAzureX1212** [DaGenix/rust-crypto#470]
Quoting the content of the `gcc` crate on crates.io:
"NOTE: This crate has been deprecated and is renamed to cc. It's recommended to not use this crate and instead use cc."

Any plans to migrate to the `cc` crate..?

**Comment by newpavlov** [comment]
This crate is unmaintained, it's strongly recommended to use other crates instead.

https://rustsec.org/advisories/RUSTSEC-2016-0005.html
