### ISSUE TITLE
What is the safest way to generate a key for Blowfish?

### ISSUE THREAD

**Issue by josecelano** [DaGenix/rust-crypto#479]
In tests, you use an [8-byte array](https://github.com/DaGenix/rust-crypto/blob/master/src/blowfish.rs#L354).

I want to generate one randomly.

Is there any recommendation or other crate to generate safe random keys for Blowfish?

**Comment by newpavlov** [comment]
You can use [`rand::OsRng`](https://docs.rs/rand/latest/rand/rngs/struct.OsRng.html) or [`rand::ThreadRng`](https://docs.rs/rand/latest/rand/rngs/struct.ThreadRng.html).

Note that the `rust-crypto` crate is [deprecated](https://rustsec.org/advisories/RUSTSEC-2016-0005.html). You can use the [blowfish](https://docs.rs/blowfish) crate instead from the [RustCrypto](https://github.com/RustCrypto) organization.
